jwt.secretKey=MTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMDEyMzQ1Njc4OTA=
frontend.url=http://localhost:4200
spring.datasource.username=root
spring.datasource.password=Vindel39!
logging.level.org.springframework.security=DEBUG

spring.kafka.producer.topic-name=classrooms
spring.kafka.producer.topic-number-replicas=1
spring.kafka.producer.topic-number-in-sync-replicas=1
