spring.kafka.producer.topic-name=classrooms
jwt.secretKey=MTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaMDEyMzQ1Njc4OTA=
frontend.url=http://localhost:4200
spring.datasource.username=root
spring.datasource.password=Vindel39!